- workflows/cellranger/cellranger_atac_create_reference.wdl
- workflows/cellranger/cellranger_create_reference.wdl
- workflows/smartseq2/smartseq2_create_reference.wdl
Create cellranger_create_reference.wdl and cellranger_atac_create_reference.wdl. 
Modify smartseq2_create_reference.wdl to add output_dir and genome fields, so that results are saved after exiting Cromwell.
> WDL for creating cellranger reference, cellranger atac reference, and smartseq2 reference

- docs/count.rst
- docs/versions.rst
- workflows/count_tools/count.wdl
- workflows/count_tools/optimus-count.wdl
* Update count_tools_optimus WDL with Optimus 2.0.0;
* In count WDL, remove ``optimus_version`` input, set ``optimus_output_loom`` default to ``true``;
* Fix bug in count_tools_optimus WDL when ``output_loom`` is false.
> Integrate Optimus 2.0.0 into count WDL

- docker/cumulus/test/Dockerfile
* Change `cumulus:test` docker image to be based on `debian`, instead of `miniconda3`.
* Reduce docker image size.
> Cumulus docker based on debian

- docs/count.rst
- docs/versions.rst
- workflows/count_tools/count.wdl
In `count_tools/count.wdl`:
* Use `quay.io/cumulus` registry by default.
* Use `config` docker image for configuration task, so that `count` docker image can be removed.
> Make count WDL use Quay images and config docker

- workflows/cellranger/cellranger_workflow.wdl
In recent Terra release (or Cromwell release), checking if an array is empty can no longer be done by accessing its first element and checking if it's null.
To be safe, I rewrote all such IF condition check by first checking if the array's length is positive, and if so, check if it's first  element is null.
> Resolve bad array access issue

- docker/demultiplexing/souporcell/2020.07/Dockerfile
- docker/demultiplexing/souporcell/2021.03/Dockerfile
* Install Python dependencies from conda as much as possible.
* Use miniconda3 v4.10.3.
* We still need Python 3.6, based on the [discussion](https://github.com/wheaton5/souporcell/issues/121) with Souporcell's author.
* Add support for AWS.
> update souporcell docker

- docs/spaceranger.rst
- workflows/spaceranger/spaceranger_count.wdl
- workflows/spaceranger/spaceranger_workflow.wdl
- workflows/star_solo/star-solo.wdl
In `star-solo.wdl`: 
* Expose `ref_index_file` and `whitelist_index_file` as workflow inputs.
* Accept custom genome reference from both GS and S3 URI.
In `spaceranger_workflow.wdl`:
* Remove `null_file` input, because its index is already in `acronym_file` file.
In `spaceranger_count.wdl`:
* Fix bug on `reorient_image` input.
> Adjust for AWS backend & SpaceRanger bug fix

- docs/starsolo.rst
- workflows/starsolo/starsolo_count.wdl
- workflows/starsolo/starsolo_workflow.wdl
Add `barcode_read` input to allow user specify which read (read1 or read2) contains cell barcodes and UMIs.
> Adjust starsolo_count for SHARE-Seq data

- docker/starsolo/2.7.10a/Dockerfile
- docs/starsolo.rst
- workflows/starsolo/index.tsv
- workflows/starsolo/starsolo_count.wdl
- workflows/starsolo/starsolo_workflow.wdl
* Add `tenX_fiveprime` type for **Assay** field in the sample sheet.
* Preset STARsolo options for 10x 5' protocol, following the discussion in [this STAR issue](https://github.com/alexdobin/STAR/issues/768) and Section "[Barcode and cDNA on the same mate](https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#barcode-and-cdna-on-the-same-mate)" in STARsolo documentation.
* Notice that if Read 1 has no more than 39 nt, we should not set `--soloStrand Reverse` option, because only Read 2 will be left after trimming, and it should be treated as single-end RNA-seq.
* Rename `output_folder` to `output_count_directory` in `starsolo_count.wdl`. 
* Update documentation.
* Add docker image for STAR v2.7.10a, but it's still under testing.
> Add 10x 5p protocol support to STARsolo WDL workflow

- workflows/cellranger/cellranger_create_reference.wdl
The `memory` input is required to use format like `"32G"`, but WDL task **run_filter_gtf** incorrectly wraps it as `"32GG"` to the runtime attribute list.
> fix bug in memory specification

- docker/chromap/0.1.5/Dockerfile
- docker/cumulus_feature_barcoding/0.7.0/Dockerfile
- docker/demultiplexing/demuxem/0.1.7/Dockerfile
- docker/starsolo/2.7.10a/Dockerfile
- docker/starsolo/2.7.9a/Dockerfile
Only Stratocumulus v0.1.5 works well with AWS backend for copy commands using wildcards.
> Upgrade Stratocumulus to v0.1.5

- workflows/starsolo/starsolo_create_reference.wdl
link memory input with '--limitGenomeGenerateRAM' option in STARsolo_create_reference workflow.
> Bug fix for STARsolo_create_reference memory limit

- workflows/cellranger/cellranger_arc_count.wdl
- workflows/cellranger/cellranger_arc_mkfastq.wdl
- workflows/cellranger/cellranger_atac_count.wdl
- workflows/cellranger/cellranger_atac_mkfastq.wdl
- workflows/cellranger/cellranger_count.wdl
- workflows/cellranger/cellranger_mkfastq.wdl
- workflows/cellranger/cellranger_multi.wdl
- workflows/cellranger/cellranger_vdj.wdl
- workflows/cellranger/cellranger_workflow.wdl
- workflows/cumulus/cumulus_adt.wdl
- workflows/demultiplexing/demultiplexing.wdl
- workflows/demultiplexing/demuxEM.wdl
- workflows/demultiplexing/popscle.wdl
- workflows/demultiplexing/souporcell.wdl
- workflows/shareseq/shareseq_workflow.wdl
- workflows/spaceranger/spaceranger_count.wdl
- workflows/spaceranger/spaceranger_mkfastq.wdl
- workflows/spaceranger/spaceranger_workflow.wdl
- workflows/starsolo/starsolo_count.wdl
- workflows/starsolo/starsolo_workflow.wdl
* `awsQueueArn` is the input to specify the Arn string of the priority queue to use in AWS backend.
> Add awsQueueArn input

- docs/cellranger/feature_barcoding.rst
- docs/cellranger/sc_atac.rst
- docs/cellranger/sc_multiomics.rst
- docs/cellranger/sc_sn_rnaseq.rst
- docs/cellranger/sc_vdj.rst
- workflows/cellranger/cellranger_arc_mkfastq.wdl
- workflows/cellranger/cellranger_atac_mkfastq.wdl
- workflows/cellranger/cellranger_mkfastq.wdl
- workflows/cellranger/cellranger_workflow.wdl
This is to solve the feature request from Broad Institute users working on their GP samples.
> Add 'mkfastq_force_single_index' input to cellranger_workflow

- docs/cellranger/sc_sn_rnaseq.rst
- docs/conf.py
- docs/starsolo.rst
- workflows/cellranger/index.tsv
- workflows/starsolo/index.tsv
- workflows/starsolo/starsolo_create_reference.wdl
- workflows/starsolo/starsolo_workflow.wdl
* Add references for CellRanger and STARsolo workflows.
* The Cellranger refs are reorganized from https://www.thepoollab.org/resources.
* The STARsolo refs are built by `starsolo_create_reference` WDL using STAR v2.7.10a.
* For details on the optimized refs, see https://www.biorxiv.org/content/10.1101/2022.04.26.489449v1.
* Set `2.7.10a` to be the default STAR version of `starsolo_workflow` and `starsolo_create_reference` WDLs.
> Add optimized GRCh38 and mm10 genome references

- docs/cellranger/build_refs.rst
- docs/cellranger/feature_barcoding.rst
- docs/cellranger/sc_atac.rst
- docs/cellranger/sc_multiomics.rst
- docs/cellranger/sc_sn_rnaseq.rst
- docs/cellranger/sc_vdj.rst
- workflows/cellranger/cellranger_atac_aggr.wdl
- workflows/cellranger/cellranger_atac_create_reference.wdl
- workflows/cellranger/cellranger_create_reference.wdl
- workflows/cellranger/cellranger_vdj_create_reference.wdl
- workflows/cellranger/cellranger_workflow.wdl
* Default cellranger version is `7.0.0`.
* Default cellranger-atac version is `2.1.0`.
* In cellranger_workflow.wdl, default of `include_introns` is `true`.
* Retire cellranger versions before `5.0.0`, as `include_introns` only works for CellRanger v5.0.0+.
> Update Cellranger versions

- workflows/cellranger/cellranger_count.wdl
- workflows/cellranger/cellranger_multi.wdl
* For Cellranger v5.0.0 - v6.1.2: `--include-introns` if `true`.
* For Cellranger v7.0.0: `--include-introns true` if `true`; `--include-introns false` otherwise.
> consider --include-introns option interface change in CellRanger v7.0.0+

- docker/config/0.3/Dockerfile
- docker/config/check_uri.py
- workflows/cellranger/cellranger_workflow.wdl
- workflows/demultiplexing/demultiplexing.wdl
- workflows/spaceranger/spaceranger_workflow.wdl
- workflows/starsolo/starsolo_workflow.wdl
* Wrap the checking code as a Python script built into `config:0.3` docker image.
* Apply the check to Cellranger, Spaceranger, STARsolo and Demultiplexing workflows.
* STARsolo workflow's config task now uses `config` docker image.
> Add output_directory check before execution

- workflows/cumulus/cumulus.wdl
- workflows/cumulus/cumulus_tasks.wdl
This is to work with Cromwell v81+ type check.
> Fix cyclic dependency on cluster.output_h5ad used for both input and output variable name

- workflows/cellranger/cellranger_arc_count.wdl
- workflows/cellranger/cellranger_atac_count.wdl
In `cellranger_atac_count.wdl` and `cellranger_arc_count.wdl`, when localizing fastq folders, they use `strato cp -r` command.
However, this would fail for GCP backend, because GCP requires creating the target local folder beforehand.
Therefore, switch to use `strato sync` command instead as it has no such extra requirement for both AWS and GCP.
> Bug fix for localizing GCP folders in ATAC and ARC count WDLs

- workflows/spaceranger/spaceranger_count.wdl
`--loupe_alignment` should be `--loupe-alignment`
> Fix an option typo in Spaceranger count

- .dockstore.yml
- docs/starsolo.rst
- workflows/starsolo/starsolo_count.wdl
- workflows/starsolo/starsolo_workflow.wdl
This is to fix the issue #371 .
Add two inputs `limitBAMsortRAM` and `outBAMsortingBinsN` to expose the corresponding STAR options.
> Enable STARsolo to handle out-of-memory in BAM sorting

- docker/demultiplexing/souporcell/2022.12/Dockerfile
- docs/demultiplexing.rst
- workflows/demultiplexing/demultiplexing.wdl
Due to [this PR](https://github.com/wheaton5/souporcell/pull/162), Souporcell 2022.12 adds additional columns `singlet_posterior` and `doublet_posterior` to `clusters.tsv` generated by troublet to achieve a better interpretation on the assignment.
Thanks to @johnyaku for bringing this info in Issue #372 .
> Add souporcell 2022.12

- docs/bcl2fastq.rst
Installing bcl2fastq from rpm on Debian images no longer works for Debian 11 or later (equivalently Ubuntu 20.04 or later).
> Update bcl2fastq docker guidance

- .dockstore.yml
- docs/cellranger/fixed_rna_profiling.rst
- workflows/cellranger/cellranger_multi.wdl
Besides keywords of preset probe set references, the workflow also accepts GS/S3 URIs of custom probe set CSV files.
> Cellranger FRP accepts custom probe set references

- workflows/spaceranger/spaceranger_count.wdl
Fix the issue when `colorizedimage` is null while only `cytaimage` is provided.
> Fix spaceranger bug on --colorizedimage

- docs/cellranger/fixed_rna_profiling.rst
- workflows/cellranger/cellranger_workflow.wdl
Cell ranger multi needs to use a dedicated parameter `multi_disk_space` which is larger for processing 10x Flex samples.
> Disk Space for Fixed RNA Profiling

- docker/cellranger-arc/2.0.2/Dockerfile
- docker/cellranger-atac/2.1.0/Dockerfile
- docker/cellranger/7.2.0/Dockerfile
- docker/cellranger/8.0.0/Dockerfile
- docker/config/0.3/Dockerfile
- docker/cumulus_feature_barcoding/0.11.3/Dockerfile
- docker/spaceranger/3.0.0/Dockerfile
- docs/cellranger/build_refs.rst
- docs/cellranger/fixed_rna_profiling.rst
- docs/cellranger/sc_sn_rnaseq.rst
- docs/conf.py
- docs/release_notes/version_2_6.rst
- docs/spaceranger.rst
- workflows/cellranger/cellranger_arc_count.wdl
- workflows/cellranger/cellranger_arc_mkfastq.wdl
- workflows/cellranger/cellranger_atac_aggr.wdl
- workflows/cellranger/cellranger_atac_count.wdl
- workflows/cellranger/cellranger_atac_create_reference.wdl
- workflows/cellranger/cellranger_atac_mkfastq.wdl
- workflows/cellranger/cellranger_vdj_create_reference.wdl
* Upgrade stratocumulus to v0.2.3 to support `*` wildcards for local backend.
* Remove `--backend` options from Cellranger-ATAC and Cellranger-ARC workflows.
* Fix a bug in `config:0.3` docker image: add read and executable permissions to `check_uri.py` file; otherwise, it would fail for HPC + Singularity use case.
* Update docs for new genome references and probe sets.
> Fix issues in Cellranger series workflows

- docker/cellranger-arc/2.0.2.custom-max-cell/Dockerfile
- docker/cellranger-arc/2.0.2/Dockerfile
- docker/cellranger-atac/2.1.0/Dockerfile
- docker/cellranger/8.0.0/Dockerfile
- docker/cellranger/8.0.1/Dockerfile
- docker/cumulus_feature_barcoding/0.11.3/Dockerfile
- docker/spaceranger/3.0.0/Dockerfile
- docs/cellranger/feature_barcoding.rst
- docs/cellranger/sc_multiomics.rst
- docs/cellranger/sc_sn_rnaseq.rst
- docs/cellranger/sc_vdj.rst
- workflows/cellranger/cellranger_workflow.wdl
- workflows/cellranger/index.tsv
* Add barcode whitelists for `SC3Pv4`, `SC5P-PE-v3` and `SC5P-R2-v3`, which are required by feature barcoding task
* Use Cell Ranger v8.0.1 by default
* Add `/usr/local/aws-cli/v2/current/bin` to `PATH` to resolve conflict with AWS Batch's auto-installed aws-cli
> Update regarding GEM-X chemistries

- docker/cellranger-arc/2.0.2.strato/Dockerfile
- docs/cellranger/sc_multiomics.rst
- docs/conf.py
- docs/release_notes/version_2_6.rst
- workflows/cellbender/frp_utils.py
- workflows/cellranger/cellranger_workflow.wdl
For `cellranger-arc` docker images:
* `2.0.2` tag uses Stratocumulus v0.1.7, which requires `--backend` option, compatible with workflow v2.6.0 or earlier.
* `2.0.2.strato` tag uses Stratocumulus v0.2.4, which drops `--backend` option, compatible with workflow v2.6.1 or later.
In `cellranger_workflow.wdl`:
* `cellranger_arc_version` has default "2.0.2.strato".
> Fix workflow issue with cellranger-arc

- docker/geomxngs_fastq_to_dcc/Dockerfile
- workflows/geomxng/geomxngs_dcc_to_count_matrix.wdl
- workflows/geomxng/geomxngs_fastq_to_dcc.wdl
Following changes were made to the geomx workflows:
- Add aws-cli path to PATH
- Update stratocumulus to 0.2.4 & remove backend from strato options
- Modify the workflow output type from String to File
- Export TMPDIR in the task to fix issues with geomxngspipeline tool
> Update Geomx workflows

- workflows/cellranger/cellranger_count.wdl
- workflows/cellranger/cellranger_multi.wdl
- workflows/cellranger/cellranger_vdj.wdl
- workflows/spaceranger/spaceranger_count.wdl
Enforce cellranger and spaceranger run with fixed memory with `--localmem` option.
This is to avoid memory preempt across tasks running on the same VM instance under AWS/GCP Batch.
> Set `--localmem` for cellranger and spaceranger workflows

- docker/cumulus_feature_barcoding/2.0.0/Dockerfile
- docs/cellranger/feature_barcoding.rst
- workflows/cellranger/cellranger_workflow.wdl
- workflows/cumulus/cumulus_adt.wdl
Cellranger workflow:
* Rename `min_read_ratio` to `read_ratio_cutoff`
* Antibody type samples now take `Reference` column values
* Upgrade `cumulus_feature_barcoding_version` default to `2.0.0`
> Upgrade to cumulus_feature_barcoding v2.0.0

- workflows/demultiplexing/demuxEM.wdl
Hello,
We had an issue with demuxEM workflow when running them in parallel on 96 cpu cores machines, they would randomly fail with segfault.
Basically, the issue is: while running in docker container, the script still was sees all 96 cores, so it defaults to running 96 cores for openblas used in sklearn/numpy. And while docker limits processor usage, it leads to go over linux's mmap limit and then leads to crash.
> fix(DemuxEM.wdl): Added environment variables to use currect number of threads to use by sklearn and numpy.

- workflows/demultiplexing/demuxEM.wdl
On AWS, demultiplexing workflow using demuxEM sometimes fails with out-of-memory error, but Cromwell/OS did not get this failure signal, and the machine keeps on running with no more execution for a long time.
This PR tries to fix the issue by enforcing the script to fail and send a unified signal to OS.
> Wrap up demuxEM command by a try-except block
