docs/cellranger.rst
workflows/cellranger/cellranger_create_reference.wdl
workflows/cellranger/index.tsv

Updated cellranger workflow reference to include build reference utilities. In addition, added two prebuilt references.

Updated references and doc

---

workflows/cellranger/cellranger_atac_create_reference.wdl
workflows/cellranger/cellranger_create_reference.wdl
workflows/cellranger/cellranger_vdj_create_reference.wdl
workflows/smartseq2/smartseq2_create_reference.wdl

* Unzip input files if needed.
* Set attributes in cellranger_create_reference as optional.
* Use escape characters in awk command.

Create Reference WDL

---

docs/drop_seq.rst
workflows/drop-seq/dropseq_align.wdl
workflows/drop-seq/dropseq_workflow.wdl

…nputs to adjust disk space allocated for STAR alignment task.

Added star_extra_disk_space and star_disk_space_multiplier workflow

---

docs/versions.rst
workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_tasks.wdl

When "run_diffmap" is set, reduce calculated diffusion map to 3D via PCA for plotting.

Fix bug on plotting Diffusion Map

---

docs/cellranger.rst
docs/versions.rst
workflows/cellranger/cellranger_atac_aggr.wdl

* Fix bugs in WDL.
* WDL passed test on local server.
* Update corresponding docs.

Finish up cellranger_atac_aggr WDL

---

docs/cumulus.rst

* Add "Load Cumulus results into Pegasus" subsection in Cumulus section.
* Add "Load Cumulus results into SCANPY" subsection in Cumulus section.
* Reformat "Load Cumulus results into Seurat" subsection.

Add loading cumulus result to Pegasus and SCANPY

---

docker/merge-fastqs/Dockerfile
docker/merge-fastqs/build.sh
docker/merge-fastqs/upload.sh
docker/pegasus-terra/0.16.8/Dockerfile
docker/pegasus-terra/0.16.8/build.sh
docker/pegasus-terra/0.16.8/upload.sh
docker/pegasus-terra/CHANGELOG.md
docker/pegasus-terra/README.md
workflows/count_tools/merge_fastqs.wdl

* Update pegasus-terra image with Pegasus 0.16.8 and scPlot 0.0.16.
* Add README.md and CHANGELOG.md for pegasus-terra image.

Update Pegasus-Terra docker image

---

docs/cumulus.rst

* Add description on ``output_seurat_h5ad`` and ``output_loom`` in "cluster outputs";
* Add description on ``output_de_h5ad`` and ``output_de_xlsx`` in "de_analysis outputs".

update cumulus docs

---

docker/cumulus/0.14.0/Dockerfile
docker/cumulus/0.14.0/build.sh
docker/cumulus/0.14.0/upload.sh

* Remove libboost-iostreams-dev

Add cumulus 0.14.0 docker image

---

docker/cumulus/0.14.0/Dockerfile
docs/cumulus.rst
docs/versions.rst
workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_tasks.wdl

* 2 new inputs in cumulus cluster: ``remap_singlets`` and ``subset_singlets`` for demultiplexed data.
* Cumulus now allows reading ``loom`` file with user-specified channel and black list.

Update Cumulus WDL for Pegasus 0.16.11

---

docker/cumulus/0.14.0/Dockerfile
docker/cumulus/0.15.0/Dockerfile
docs/cumulus.rst

* Use hnswlib 0.3.4.
* Update docs.

Update for cumulus 0.14.0

---

docker/cumulus/0.15.0/Dockerfile

* Update pegasuspy to 0.17.0, with anndata and pandas updated;
* Update statsmodels to avoid future warning with pandas 1.0+;
* Update h5py to avoid conflict with anndata;
* Update bokeh to avoid conflict with holoviews;
* Update loompy;
* Fix version of scplot.

Update cumulus 0.15.0

---

docs/versions.rst
workflows/count_tools/count.wdl
workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_hashing_cite_seq.wdl
workflows/cumulus/cumulus_subcluster.wdl

* Update cumulus WDLs for cumulus 0.15.0;
* Fix bug in count WDL.

Update Cumulus and Count WDLs

---

docs/cumulus.rst
docs/versions.rst
workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_subcluster.wdl
workflows/cumulus/cumulus_tasks.wdl

* Separate GS url from `output_name` to be `output_directory`.

Update cumulus WDL for Terra data table

---

docs/versions.rst
workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_tasks.wdl

* Attach "/" to `dest` to enforce `gsutil cp` to copy files to the destination folder, rather than renaming.

Fix bug in cumulus

---

docker/pegasus-terra/0.17.1/Dockerfile
docker/pegasus-terra/CHANGELOG.md
docker/pegasus-terra/README.md

* Create `pegasus-terra:0.17.1` docker image.

Update pegasus-terra docker

---

docker/cumulus/1.0.0/Dockerfile
docs/cumulus.rst
docs/versions.rst
workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_tasks.wdl

* Remove `auc` and `mwu` inputs in Cumulus de_analysis step.
* Use `pegasus aggregate_matrix` command in aggregate_matrices step.
* Update API in de_analysis and plot steps' implementation with latest Pegasus.
* Remove `fisher` from Cumulus docker; add `demuxEM`.
* Update docs.

update cumulus with latest pegasus

---

workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_tasks.wdl

* Allow two types of `calc_signature_scores` input:
* String for preset gene sets of Pegasus;
* Google bucket URL of user-specified gene set GMT file.

Update signature score calculation

---

workflows/cellranger/cellranger_vdj.wdl
workflows/cellranger/cellranger_workflow.wdl

This pull request should resolve issue #125 
Please let me know what you think!

add option vdj_chain to cellranger_workflow

---

docs/cumulus.rst
docs/release_notes.rst
docs/versions.rst
workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_tasks.wdl

* In `cumulus/cumulus_tasks.wdl`, `--marker-file` option should be updated to `--markers`.
* Update `cumulus/cumulus.wdl` with import from new snapshot of `cumulus/cumulus_tasks` WDL.
* Update docs accordingly.

Bug fix on Cumulus WDL

---

workflows/cellranger/spaceranger_mkfastq.wdl

add spaceranger

---

workflows/cellranger/spaceranger_mkfastq.wdl

Fix an issue on pull request #147 .

Use gsutil for cloud usage in spaceranger_mkfastq WDL

---

docker/cumulus_feature_barcoding/0.6.0/Dockerfile
docs/versions.rst
workflows/cellranger/cellranger_arc_count.wdl
workflows/cellranger/cellranger_arc_mkfastq.wdl
workflows/cellranger/cellranger_atac_aggr.wdl
workflows/cellranger/cellranger_atac_count.wdl
workflows/cellranger/cellranger_atac_create_reference.wdl
workflows/cellranger/cellranger_atac_mkfastq.wdl
workflows/cellranger/cellranger_count.wdl
workflows/cellranger/cellranger_create_reference.wdl
workflows/cellranger/cellranger_mkfastq.wdl
workflows/cellranger/cellranger_vdj.wdl
workflows/cellranger/cellranger_vdj_create_reference.wdl
workflows/cellranger/cellranger_workflow.wdl
workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_adt.wdl
workflows/cumulus/cumulus_tasks.wdl
workflows/demultiplexing/demultiplexing.wdl
workflows/demultiplexing/demuxEM.wdl
workflows/demultiplexing/demuxlet.wdl
workflows/demultiplexing/souporcell.wdl
workflows/smartseq2/smartseq2_create_reference.wdl

* Allow white spaces within output directory and sample ID (name).
* Update `cumulus_adt` WDL to account for necessary conversion of cell barcodes for 10x genomics data.

WDL update

---

docs/demultiplexing.rst
docs/versions.rst
workflows/demultiplexing/demultiplexing.wdl
workflows/demultiplexing/popscle.wdl

Besides, remove `geno_error` and thus use its default.

Expose more fields in popscle to demultiplexing 

---

docker/cumulus/1.3.0/Dockerfile
docker/cumulus_feature_barcoding/0.6.0/Dockerfile
docs/cumulus.rst
docs/versions.rst
workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_tasks.wdl

* Fix bug in *cumulus_adt* WDL when detecting totalA or totalBC chemistry.
* Fix bug in *cumulus* WDL: `remap_singlets` and `subset_singlets` don't work in the case of sample sheet format input.

Cumulus and Cumulus_ADT bug fix

---

workflows/star_solo/star-solo.wdl

added option to specify custom Bead structure re: BC length & UMI length

Update star-solo.wdl to accommodate custom barcode & UMI lengths

---

docker/cumulus/1.4.1/Dockerfile
docker/cumulus/1.4.2/Dockerfile
docs/versions.rst
workflows/cumulus/cumulus.wdl
workflows/cumulus/cumulus_tasks.wdl

* Add `run_nmf` and `nmf_n` inputs.
* Update Pegasus to v1.4.2.

Add NMF-related features to Cumulus WDL

---

docker/cumulus/1.4.3/Dockerfile

Updated Dockerfile:
- `pegasuspy` to v1.4.3
- Added `stratocumulus`
- Updated google-cloud-sdk to version `354.0.0-0`

Integrate Stratocumulus into Cumulus docker image

---

workflows/cellranger/cellranger_workflow.wdl
workflows/demultiplexing/demultiplexing.wdl
workflows/star_solo/star-solo.wdl

Similarly as in cellranger_workflow WDL, resolve the potential issues in the following WDLs:
* `demultiplexing/demultiplexing.wdl`;
* `star_solo/star-solo.wdl`.

resolve bad array indexing issue

---

docker/cumulus_feature_barcoding/0.6.0/Dockerfile

updating cumulus_feature_barcoding with stratocumulus

---

workflows/spaceranger/spaceranger_count.wdl
workflows/spaceranger/spaceranger_mkfastq.wdl
workflows/spaceranger/spaceranger_workflow.wdl

- Added stratocumulus command to Spaceranger workflows

added stratocumulus command

---

docker/demultiplexing/demuxem/0.1.6/Dockerfile
docker/demultiplexing/popscle/0.1b/Dockerfile
docker/demultiplexing/popscle/2021.05/Dockerfile
docker/demultiplexing/souporcell/2020.07/Dockerfile
docker/demultiplexing/souporcell/2021.03/Dockerfile
docker/spaceranger/1.2.1/Dockerfile
docker/spaceranger/1.3.0/Dockerfile
workflows/demultiplexing/demultiplexing.wdl
workflows/spaceranger/spaceranger_workflow.wdl

- Updated demuxEM (0.1.6), souporcell (2020.07 and 2021.03), and popscle (0.1b and 2021.05) dockers with strato & updated google cloud sdk
- Updated spaceranger (1.3.0) Docker with strato & updated google cloud sdk
- Added strato commands to wdls of all above

Added stratocumulus to spaceranger, demultiplexing & updated dockers

---

docker/cellranger-arc/2.0.0/Dockerfile
docker/cellranger-atac/2.0.0/Dockerfile
docker/cellranger/6.0.2/Dockerfile
docker/cellranger/6.1.1/Dockerfile
docker/spaceranger/1.3.0/Dockerfile

- Added AWS CLI
- Correct version numbers for packages involved

adding aws cli and correcting version numbers

---

docker/cumulus_feature_barcoding/0.6.0/Dockerfile
docker/demultiplexing/demuxem/0.1.6/Dockerfile
docker/demultiplexing/popscle/0.1b/Dockerfile
docker/demultiplexing/popscle/2021.05/Dockerfile
docker/starsolo/2.7.6a/Dockerfile

Added aws cli to:
- Starsolo
- cumulus feature barcoding
- demuxem
- popcle

adding aws cli

---

workflows/cellranger/cellranger_workflow.wdl
workflows/cumulus/cumulus.wdl
workflows/spaceranger/spaceranger_workflow.wdl

- Added relative paths to cellranger_workflow.wdl
- Added relative paths to spaceranger_workflow.wdl
- Added relative paths to cumulus.wdl

relative paths for import statements

---

workflows/cellranger/cellranger_arc_mkfastq.wdl
workflows/cellranger/cellranger_mkfastq.wdl

fixing strato commands in mkfastq

---

docs/examples/example_cellplex.rst
docs/examples/index.rst

* Add documentation on CellPlex example.
* The example uses `altocumulus` to submit jobs to a Cromwell server.

Add CellPlex example

---

docker/demultiplexing/demuxem/0.1.7/Dockerfile
docs/demultiplexing.rst
workflows/demultiplexing/demultiplexing.wdl

- make Demuxem v0.1.7 default
- update docker

adding support for Demuxem v0.1.7

---

workflows/spaceranger/spaceranger_workflow.wdl

- adding gcp as default backend for spaceranger

added gcp as default backend for spaceranger workflow

---

docker/cellranger/6.0.2/Dockerfile
docker/cellranger/6.1.1/Dockerfile
workflows/cellranger/cellranger_count.wdl
workflows/cellranger/cellranger_mkfastq.wdl

- copies over fastqs on per sample basis using wildcards
- updating cellranger docker files with stratocumulus version 0.1.3

handles all fastqs in 1 folder for cellranger count

---

docker/spaceranger/1.3.0/Dockerfile
workflows/spaceranger/spaceranger_count.wdl
workflows/spaceranger/spaceranger_mkfastq.wdl

- copy on per sample basis using wildcards since NGS style output contains all fastqs in 1 folder
- updating stratocumulus to v0.1.3

handle all fastqs in 1 folder for spaceranger count

---

workflows/cumulus/cumulus_adt.wdl

- finds fastqs per sample basis for ADT samples
- adding appropriate modules

All fastqs in one folder for adt

---

workflows/cellranger/cellranger_arc_count.wdl
workflows/cellranger/cellranger_arc_mkfastq.wdl
workflows/cellranger/cellranger_atac_count.wdl
workflows/cellranger/cellranger_atac_mkfastq.wdl
workflows/cellranger/cellranger_count.wdl
workflows/cellranger/cellranger_multi.wdl
workflows/cellranger/cellranger_vdj.wdl
workflows/cumulus/cumulus_adt.wdl

Adding support to handle all fastqs in one folder to following modules:
-cellranger count
-atac
-arc
-vdj
-adt

adding try blocks where needed

---

workflows/cumulus/cumulus_adt.wdl

- Corrected CalledProcessError call in os

removing CalledProcessError from os

---

docs/examples/example_gex_citeseq.rst
docs/examples/index.rst

- Added tutorial on analysis of citeseq, hashing and gex dataset.

adding citseq,hashing,gex tutorial

---

workflows/cellranger/cellranger_arc_count.wdl
workflows/cellranger/cellranger_atac_count.wdl
workflows/cellranger/cellranger_count.wdl
workflows/cellranger/cellranger_multi.wdl
workflows/cellranger/cellranger_vdj.wdl
workflows/cumulus/cumulus_adt.wdl
workflows/spaceranger/spaceranger_count.wdl

- send error to stdout
- send stdout to devnull

strato exists traceback to devnull

---

docker/chromap/0.1.3/Dockerfile

Chromap docker

---

workflows/cellranger/cellranger_atac_create_reference.wdl
workflows/cellranger/cellranger_vdj_create_reference.wdl

- added slash for strato cp command

adding slash for copy

---

workflows/chromap/chromap.wdl

- adding wdl for chromap mapping

Chromap dev

---

workflows/cellranger/cellranger_arc_count.wdl

- concat directory and file
- adding check_call statement

Fix arc workflow

---

workflows/chromap/chromap.wdl

Sort filtered list

---

docs/chromap.rst
workflows/chromap/chromap.wdl

- TagAlign => tagalign
- --threads => -t
- --num_thread_t => --num_cpu
- changed chromap doc

Fix chromap

---

docker/cellranger-atac/1.2.0/Dockerfile

-adding support for cellranger atac 1.2.0

adding support for atac 1.2.0

---

docs/chromap.rst
workflows/chromap/chromap.wdl

- changed defaults in wdl
- changed defaults in doc

changed defaults after benchmarking

---

docker/shareseq/shareseq_mkfastq/0.1.0/Dockerfile
workflows/shareseq/shareseq_mkfastq.wdl

- removed reorg code from mkfastq

removed reorg code from mkfastq

---

docker/shareseq/shareseq_reorg/0.1.0/Dockerfile
workflows/shareseq/shareseq_reorg.wdl

- file patterns to shareseq_barcodes_reorg code
- copy over fastqs

Shareseq reorg

---

workflows/chromap/chromap.wdl

-Update chromap to accept shell wildcard pattern for R1,R2 and barcode search

Chromap wildcard

---

workflows/starsolo/starsolo_count.wdl

Handle the parameter overwriting by Cumulus, because STAR itself does not apply this automatically, but instead throws exception about duplicated options.

resolve duplicated option issue

---

docker/shareseq/shareseq_mkfastq/scripts/shareseq2bcl

-added missing = for comparison

added missing =

---

workflows/cellranger/cellranger_create_reference.wdl
workflows/cellranger/cellranger_workflow.wdl
workflows/demultiplexing/demultiplexing.wdl
workflows/spaceranger/spaceranger_workflow.wdl
workflows/starsolo/starsolo_workflow.wdl

Apply this operation for the following workflows:
* cellranger_workflow
* spaceranger_workflow
* starsolo_workflow
* demultiplexing

Strip whitespaces for column names in the sample sheet

---

docs/starsolo.rst
workflows/starsolo/index.tsv

- updated index.tsv for starsolo
- updated reference section with mouse-human

adding new mouse human ref

---

docker/shareseq/shareseq_mkfastq/0.1.0/Dockerfile
docker/shareseq/shareseq_mkfastq/scripts/remove_prefix.sh
workflows/shareseq/shareseq_mkfastq.wdl

- separating out bash code into remove_prefix.sh
- loop array
- handling cut properly

Shareseq mkfastq bug

---

workflows/chromap/chromap_mapping.wdl

-read_format parameter put in extend instead of append

extend instead of append

---

docker/chromap/0.1.5/Dockerfile
workflows/chromap/chromap_mapping.wdl
workflows/shareseq/shareseq_workflow.wdl

- Built new chromap 0.1.5 docker
- made default version in chromap & shareseq

Chromap new

---

docs/chromap.rst
docs/shareseq/gex_atac.rst

- updated chromap and shareq doc to chromap 0.1.5
- updated chromap doc with patterns rather than identifiers

change to new chromap version; change in identifier

---

docker/cellranger-arc/2.0.1/Dockerfile

Update following packages in cellranger-arc
- cellranger-arc 2.0
- stratocumulus 1.5.0
- aws cli 2.4.20
- google-cloud-cli 375.0.0-0

update aws sdk strato arc

---

docker/trust4/master/Dockerfile

adding trust4 docker

---

docker/trust4/master/Dockerfile

-symlink required perl scripts
-make perl scripts executable

adding wget

---

workflows/trust4/trust4_create_reference.wdl

added create ref for trust4

---

workflows/cellranger/cellranger_arc_mkfastq.wdl
workflows/cellranger/cellranger_atac_mkfastq.wdl
workflows/cellranger/cellranger_create_reference.wdl
workflows/cellranger/cellranger_mkfastq.wdl
workflows/cellranger/cellranger_vdj.wdl
workflows/cellranger/cellranger_vdj_create_reference.wdl
workflows/cumulus/cumulus_tasks.wdl
workflows/demultiplexing/demuxEM.wdl
workflows/demultiplexing/popscle.wdl
workflows/demultiplexing/souporcell.wdl
workflows/shareseq/shareseq_mkfastq.wdl
workflows/spaceranger/spaceranger_count.wdl
workflows/spaceranger/spaceranger_mkfastq.wdl

Python 3.9 no longer allows use `is` or `is not` to compare with values other than `None`. 
Use `==` and `!=` instead.

Make WDLs work with Python3.9 syntax restriction

---

docker/cellranger/6.1.2/Dockerfile
docker/spaceranger/1.3.1/Dockerfile

* Use the latest way of installing `google-cloud-sdk`.
* Upgrade stratocumulus version.

Update Cellranger and Spaceranger dockers

---

workflows/cellranger/cellranger_workflow.wdl

Adding output directory path check

---

docker/cellbender/0.2.0/Dockerfile
workflows/cellbender/cellbender.wdl

- Modify from BSD-3-Clause licensed CellBender [repo](https://github.com/broadinstitute/CellBender).
- Accept multiple samples.

Cellbender wdl

---

.dockstore.yml
docs/cellranger/sc_atac.rst
workflows/cellranger/cellranger_atac_count.wdl
workflows/cellranger/cellranger_workflow.wdl

Add support on analyzing only the ATAC part of 10x multiome data.

Sergio dev

---

docker/cumulus_feature_barcoding/0.11.0/Dockerfile
docs/cellranger/feature_barcoding.rst
workflows/cellranger/cellranger_workflow.wdl

* Add docker image.
* In `cellranger_workflow.wdl`, set `cumulus_feature_barcoding_version` default to `0.11.0`.
* Update documentation accordingly.

Upgrade cumulus_feature_barcoding to 0.11.0

---

.dockstore.yml
workflows/spaceranger/spaceranger_count.wdl

During the update to 2.0.0, some minor bugs were identified and this PR fix them

Minor bugs

---

.dockstore.yml
workflows/cellranger/index.tsv
workflows/spaceranger/spaceranger_count.wdl

* Fix format issue in `workflows/cellranger/index.tsv`.
* Correct the logic of applying `--reorient-images`.

Finish up Spaceranger update to v2.0.0

---

docker/cellranger-arc/2.0.2/Dockerfile

upgraded cellranger-arc to 2.0.2

upgrade cellranger arc

---

docker/cellranger/7.0.1/Dockerfile

cellranger - 7.0.1

---

docs/cellranger/fixed_rna_profiling.rst
workflows/cellranger/index.tsv

https://support.10xgenomics.com/fixed-rna-profiling/probe-sets/mouse-probe-set

Add FRP mouse probeset

---

docker/cumulus_feature_barcoding/0.11.1/Dockerfile
docs/cellranger/feature_barcoding.rst
workflows/cellranger/cellranger_workflow.wdl

https://github.com/lilab-bcb/cumulus_feature_barcoding/releases/tag/0.11.1

Upgrade cumulus_feature_barcoding to v0.11.1 by default

---

docker/starsolo/2.7.10b/Dockerfile
workflows/starsolo/starsolo_workflow.wdl

* Upgrade 2.7.10a from [220601](https://github.com/alexdobin/STAR/releases/tag/2.7.10a_alpha_220601) to [220818](https://github.com/alexdobin/STAR/releases/tag/2.7.10a_alpha_220818).
* Add 2.7.10b, which points to [230301](https://github.com/alexdobin/STAR/releases/tag/STAR_2.7.10b_alpha_230301).
* Use 2.7.10b by default.

Upgrade star version to 2.7.10b

---

.dockstore.yml
workflows/cellranger/cellranger_workflow.wdl

Don't add ProbeSet if it's null.

Bug fix for FRP case

---

.dockstore.yml
docker/cellranger/7.2.0/Dockerfile
docker/spaceranger/2.1.1/Dockerfile
docs/cellranger/build_refs.rst
docs/cellranger/feature_barcoding.rst
docs/cellranger/fixed_rna_profiling.rst
docs/cellranger/sc_multiomics.rst
docs/cellranger/sc_sn_rnaseq.rst
docs/cellranger/sc_vdj.rst
docs/spaceranger.rst
workflows/cellranger/cellranger_count.wdl
workflows/cellranger/cellranger_create_reference.wdl
workflows/cellranger/cellranger_mkfastq.wdl
workflows/cellranger/cellranger_multi.wdl
workflows/cellranger/cellranger_vdj.wdl
workflows/cellranger/cellranger_workflow.wdl
workflows/spaceranger/spaceranger_count.wdl
workflows/spaceranger/spaceranger_mkfastq.wdl
workflows/spaceranger/spaceranger_workflow.wdl

Also upgrade stratocumulus to v0.2.1, which removes `--backend` option. So all the corresponding WDL workflows have to be updated accordingly.

Upgrade Cellranger to v7.2.0; Upgrade Spaceranger to v2.1.1

---

docker/config/0.4/Dockerfile

In this docker image:
* Upgrade numpy, pandas and Xlsxwriter packages to current latest versions;
* Add `monitor_script.sh`;
* Add boto3 package for list operations without localizing S3 files.

Config 0.4

---

docker/monitor_script.sh

Currently only support NVIDIA GPUs.

Monitor GPU memory usage

---

docker/geomxngs_dcc_to_count_matrix/1.0.0/src/create-counts.py

handle duplicates in metadata

---

.dockstore.yml
docker/cellranger/8.0.0/Dockerfile
docker/cumulus_feature_barcoding/0.11.3/Dockerfile
docker/spaceranger/3.0.0/Dockerfile
docs/cellranger/feature_barcoding.rst
docs/cellranger/fixed_rna_profiling.rst
docs/cellranger/sc_multiomics.rst
docs/cellranger/sc_sn_rnaseq.rst
docs/cellranger/sc_vdj.rst
docs/spaceranger.rst
workflows/cellranger/cellranger_count.wdl
workflows/cellranger/cellranger_multi.wdl
workflows/cellranger/cellranger_workflow.wdl
workflows/spaceranger/spaceranger_count.wdl
workflows/spaceranger/spaceranger_workflow.wdl

* Software version bumping up
* Adapt to `--create-bam` option, which is an required option

Support Cell Ranger v8.0.0 and Space Ranger v3.0.0

---

docker/cellranger-arc/2.0.2.custom-max-cell/Dockerfile
docker/cellranger-arc/2.0.2.custom-max-cell/__init__.py

cellranger-arc with customized max-cell argument

Add docker image with customized max-cell argument

---

docker/starsolo/2.7.11b/Dockerfile
docs/starsolo.rst
workflows/smartseq2/smartseq2.wdl
workflows/starsolo/starsolo_create_reference.wdl
workflows/starsolo/starsolo_workflow.wdl

For SS2:
* Add `strandedness` option
For STARsolo:
* Upgrade to v2.7.11b

Update SmartSeq2 and STARsolo workflows

---

docker/spaceranger/3.1.3/Dockerfile

* Add `spaceranger:3.1.3` docker image
* Make `cellranger:7.1.0` docker work with GCP Batch

Upgrade spaceranger to 3.1.3
